CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT');
CREATE TABLE "tuitions" ("id" TEXT NOT NULL, "tutor_id" TEXT NOT NULL, "name" TEXT NOT NULL, "default_fee" DECIMAL(10,2) NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "tuitions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "tuitions_tutor_id_key" ON "tuitions"("tutor_id");
ALTER TABLE "classes" ADD COLUMN "tuition_id" TEXT;
ALTER TABLE "classes" ADD COLUMN "tutor_name" TEXT;
ALTER TABLE "classes" ADD COLUMN "start_time" TIMESTAMP(3);
ALTER TABLE "classes" ADD COLUMN "end_time" TIMESTAMP(3);
ALTER TABLE "classes" ADD COLUMN "days_of_week" TEXT;
CREATE INDEX "classes_tuition_id_idx" ON "classes"("tuition_id");
ALTER TABLE "notices" ADD COLUMN "tuition_id" TEXT;
ALTER TABLE "notices" ADD COLUMN "content" TEXT;
CREATE INDEX "notices_tuition_id_idx" ON "notices"("tuition_id");
CREATE TABLE "students_info" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "tuition_id" TEXT NOT NULL, "grade_class" TEXT, "joining_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "custom_fee" DECIMAL(10,2), CONSTRAINT "students_info_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "students_info_user_id_key" ON "students_info"("user_id");
CREATE INDEX "students_info_tuition_id_idx" ON "students_info"("tuition_id");
CREATE TABLE "attendance" ("id" TEXT NOT NULL, "class_id" TEXT NOT NULL, "student_id" TEXT NOT NULL, "date" TIMESTAMP(3) NOT NULL, "status" "AttendanceStatus" NOT NULL, CONSTRAINT "attendance_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "attendance_class_id_student_id_date_key" ON "attendance"("class_id", "student_id", "date");
CREATE INDEX "attendance_student_id_idx" ON "attendance"("student_id");
CREATE INDEX "attendance_class_id_idx" ON "attendance"("class_id");
CREATE TABLE "fee_payments" ("id" TEXT NOT NULL, "student_id" TEXT NOT NULL, "tuition_id" TEXT NOT NULL, "amount" DECIMAL(10,2) NOT NULL, "payment_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "for_month" TEXT NOT NULL, "next_due_date" TIMESTAMP(3), "status" "TransactionStatus" NOT NULL DEFAULT 'PAID', CONSTRAINT "fee_payments_pkey" PRIMARY KEY ("id"));
CREATE INDEX "fee_payments_student_id_idx" ON "fee_payments"("student_id");
CREATE INDEX "fee_payments_tuition_id_idx" ON "fee_payments"("tuition_id");
CREATE INDEX "fee_payments_for_month_idx" ON "fee_payments"("for_month");
ALTER TABLE "tuitions" ADD CONSTRAINT "tuitions_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "classes" ADD CONSTRAINT "classes_tuition_id_fkey" FOREIGN KEY ("tuition_id") REFERENCES "tuitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notices" ADD CONSTRAINT "notices_tuition_id_fkey" FOREIGN KEY ("tuition_id") REFERENCES "tuitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "students_info" ADD CONSTRAINT "students_info_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "students_info" ADD CONSTRAINT "students_info_tuition_id_fkey" FOREIGN KEY ("tuition_id") REFERENCES "tuitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students_info"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "fee_payments" ADD CONSTRAINT "fee_payments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students_info"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "fee_payments" ADD CONSTRAINT "fee_payments_tuition_id_fkey" FOREIGN KEY ("tuition_id") REFERENCES "tuitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
